# -*- coding: utf-8 -*-
"""실습2 - 레모네이드 판매 예측.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/github/blackdew/tensorflow1/blob/master/practice2-lemonade.ipynb

# 레모네이드 판매 예측
- github csv url: https://raw.githubusercontent.com/blackdew/tensorflow1/master/csv/lemonade.csv
"""

# 라이브러리 사용
import tensorflow as tf
import pandas as pd

# 데이터를 준비합니다.
파일경로 = 'csv/lemonade.csv'
레모네이드 = pd.read_csv(파일경로)
print(레모네이드.head())

# 종속변수, 독립변수
독립 = 레모네이드[['온도']]
종속 = 레모네이드[['판매량']]
print(독립.shape, 종속.shape)

# 모델을 만듭니다.
X = tf.keras.layers.Input(shape=[1])
Y = tf.keras.layers.Dense(1)(X)
model = tf.keras.models.Model(X, Y)
model.compile(loss='mse')

# 모델을 학습시킵니다. 
model.fit(독립, 종속, epochs=10000, verbose=0)
model.fit(독립, 종속, epochs=10)

# fit = 모델을 학습한다.
# epochs = 몇 번 반복해서 학습을 할 것인지.
# loss = 학습이 얼마나 진행되었는지 알려주는 지표.
# (예측 - 결과)^2 -> 즉, 예측과 결과가 모두 같으면 0이 된다.

# 모델을 이용합니다. 
print(model.predict(독립))
print(model.predict([[15]]))
